### ISSUE TITLE
Issues uploading media

### ISSUE THREAD

**Issue by Crentist** [zooniverse/Panoptes#1761]
I'm having trouble whenever I try to upload any media through the frontend (like changing a project's logo).

![erroruploadingpanoptes](https://cloud.githubusercontent.com/assets/7231917/14431188/f6afa4fc-ffda-11e5-8b0a-8e339af98172.png)

From what I can gather, you upload media to an Amazon S3 Bucket, and since I have my own, I'd like to use it, but I can't find anywhere in the config files where to change this. Am I missing something here?

**Comment by marten** [comment]
The bucket is configured through the [MediaStorage](https://github.com/zooniverse/Panoptes/blob/master/app/services/media_storage.rb), which is set up using `config/storage.yml`. The template you'll find in the repo doesn't really explain that too well, here's what we're using in production (AWS client credentials get automatically assigned):

```
production:
  adapter: aws
  bucket: zooniverse-static
  prefix: panoptes-uploads.zooniverse.org/production/
```

**Comment by camallen** [comment]
also see the secion, `Setting AWS Credentials` in http://docs.aws.amazon.com/sdk-for-ruby/latest/DeveloperGuide/aws-ruby-sdk-getting-started.html

we use env variables in the container running the app, http://docs.aws.amazon.com/sdk-for-ruby/latest/DeveloperGuide/aws-ruby-sdk-getting-started.html#aws-ruby-sdk-credentials-environment

**Comment by Crentist** [comment]
Apparently I managed to set up the config in `storage.yml` with my credentials, but I'm still getting the same error as before (as seen in the screenshot above). How can I make sure that I actually set everything up correctly? Is it possible that I also need to change something in the front-end code? Thanks for your answers!

**Comment by camallen** [comment]
Don't put the aws credentials in the `storage.yml`, put then in to env variables of the session / cmd that runs the api.

As per [the docs](http://docs.aws.amazon.com/sdk-for-ruby/latest/DeveloperGuide/aws-ruby-sdk-getting-started.html#aws-ruby-sdk-credentials-environment) linked above.
> Set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.

>Use the export command to set these variables on a Unix-based systems, such as Linux or OS X. The following example sets the value of your access key to your_access_key_id and the value of your secret access key to your_secret_access_key.

If running under docker-compose then you can edit the docker-compose env variables for the api [here](https://github.com/zooniverse/Panoptes/blob/4bee5fcac24355c24d6a2caebd4e0b463c1af1ca/docker-compose.yml#L42), perhaps something like:

```
panoptes:
  dockerfile: Dockerfile.dev
  build: ./
  volumes:
    - ./:/rails_app
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=development"
    - "CELLECT_ON=true"
    - "CELLECT_MIN_POOL_SIZE=100"
    - "ATTENTION_REDIS_URL=redis://redis:6379/1"
    - "AWS_ACCESS_KEY_ID=your_access_key_id"
    - "AWS_SECRET_ACCESS_KEY=your_secret_key"
  links:
    - redis:redis
    - postgres:pg
```

If running manually outside of docker you'll have to start rails with the env vars exported to the session running the process `export AWS_ACCESS_KEY_ID=your_key_id` or just set the env var at runtime, 
`AWS_ACCESS_KEY_ID=key_id AWS_SECRET_ACCESS_KEY=secret_key bundle exec puma -C config/puma.rb`
