### ISSUE TITLE
Updating media URLs/prefixes

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1763]
Currently we configure storage with something like:

```yaml
production:
  adapter: aws
  bucket: zooniverse-static
  prefix: panoptes-uploads.zooniverse.org/production/
```

And we assume the path starts with an FQDN here: https://github.com/zooniverse/Panoptes/blob/master/app/services/media_storage/aws_adapter.rb#L46

To make this more flexible (for both ourselves and third parties) we should instead specify the domain name (and possibly the prefix) separately:

```yaml
production:
  adapter: aws
  bucket: zooniverse-static
  prefix: panoptes-uploads.zooniverse.org/production/
  http_prefix: https://panoptes-uploads.zooniverse.org/production/
```

For our current config this does look more redundant, but when we move the media to a different bucket as planned the config becomes:

```yaml
production:
  adapter: aws
  bucket: panoptes-storage
  prefix: production/
  http_prefix: https://panoptes-uploads.zooniverse.org/production/
```
